### ISSUE TITLE
Translation of disconnect reason to described reason

### ISSUE THREAD

**Issue by ArJay60** [bertmelis/espMqttManager#8]
Hi,

Using your library I encounter a problem. Disconnects from an MQTT server with reason 5 and 7. Can you explain where these integers refer to? Something like 5 = authentication fail.

Using: void onMqttDisconnect(espMqttClientTypes::DisconnectReason reason)

Regards,
Richard

**Comment by bertmelis** [comment]
The error codes are defined in the espMqttclient library: https://github.com/bertmelis/espMqttClient/blob/main/src/TypeDefs.h#L20

You can convert the error code to `const char*` so you can print them to `Serial`: https://github.com/bertmelis/espMqttClient/blob/main/src/TypeDefs.h#L50

**Comment by bertmelis** [comment]
```cpp
void myDisconnectHandler(espMqttClientTypes::DisconnectReason reason) {
  Serial.print("MQTT disconnected, reason: ");
  Serial.println(espMqttClientTypes::errorToString(reason));
  startReconnectLogic();
}
```
